name: error-free-text

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: error-free-text-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d error-free-text-db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  error-free-text:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: error-free-text
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy