spring:
  application:
    name: error-free-text
  datasource:
    url:  jdbc:postgresql://localhost:5433/error-free-text-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

yandex:
  api:
    url: https://speller.yandex.net/services/spellservice.json
    connect-timeout: 5000
    read-timeout: 10000
    max-text-size: 10000

scheduler:
  fixed-delay: 300000 # 5 minutes